import { createFileRoute } from "@tanstack/react-router";
import React from "react";

export const Route = createFileRoute("/login")({
  component: LoginComponent,
});

function LoginComponent() {
  return (
    <div
      className="
      w-screen 
      h-screen 
      flex 
      justify-center 
      items-center 
      bg-gray-50
    "
    >
      <div
        className="
        flex 
        flex-col 
        items-center
      "
      >
        <div
          className="
          flex 
          items-center 
          mb-8
        "
        >
          <img
            src="/logo.png"
            alt="logo"
            className="
              h-10 
              mr-2
            "
          />
          <h1
            className="
            text-3xl 
            m-0
          "
          >
            BOGGLE
          </h1>
        </div>
        <div
          className="
          w-full 
          max-w-[360px] 
          flex 
          flex-col 
          gap-3
        "
        >
          <input
            type="text"
            placeholder="아이디"
            className="
              w-full 
              px-4 
              py-3 
              text-[15px] 
              border 
              border-gray-300 
              rounded-lg 
              bg-white
            "
          />
          <input
            type="password"
            placeholder="비밀번호"
            className="
              w-full 
              px-4 
              py-3 
              text-[15px] 
              border 
              border-gray-300 
              rounded-lg 
              bg-white
            "
          />
          <button
            className="
            w-full 
            py-3 
            text-[15px] 
            bg-blue-500 
            text-white 
            border-none 
            rounded-lg 
            cursor-pointer 
            mt-1
          "
          >
            로그인
          </button>
          <button
            className="
            w-full 
            py-3 
            text-[15px] 
            bg-gray-50 
            border 
            border-gray-300 
            rounded-lg 
            cursor-pointer
          "
          >
            회원가입
          </button>
        </div>
      </div>
    </div>
  );
}
