import { createFileRoute } from "@tanstack/react-router";
import Layout from "../component/Layout";
import React from "react";

export default function Post() {
  return (
    <Layout>
      <form
        className="
        max-w-[500px] 
        mx-auto 
        mt-10 
        flex 
        flex-col 
        gap-3.5
      "
      >
        <div
          className="
        bg-gray-300
        h-[250px]
        w-full
        rounded-lg 
        mb-2
      "
        />
        <h1
          className="
          text-[40px] 
          font-bold 
          mb-2
        "
        >
          제목
        </h1>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          제목
          <p>
            <input
              className="
                w-full 
                text-[15px] 
                p-1.5 
                rounded-md 
                border-2 
                border-gray-800 
                mt-1
              "
            />
          </p>
        </label>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          인원
          <p>
            <input
              className="
                w-[70px] 
                text-[15px] 
                p-1.5 
                rounded-md 
                border-2 
                border-gray-800 
                mt-1
              "
            />
          </p>
        </label>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          기간
          <p>
            <input
              className="
                w-[90px] 
                text-[15px] 
                p-1.5 
                rounded-md 
                border-2 
                border-blue-400 
                mt-1
              "
            />
          </p>
        </label>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          내용
          <p>
            <textarea
              className="
                w-full 
                text-[15px] 
                p-1.5 
                rounded-lg 
                border-2 
                border-gray-800 
                mt-1 
                resize-y
              "
            />
          </p>
        </label>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          이미지 추가
          <p>
            <input
              type="file"
              className="
                w-full 
                text-[15px] 
                p-1.5 
                rounded-md 
                border-2 
                border-gray-800 
                mt-1
              "
            />
          </p>
        </label>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          분류 태그
          <p>
            <input
              className="
                w-[100px] 
                text-[15px] 
                p-1.5 
                rounded-md 
                border-2 
                border-blue-400 
                mt-1
              "
            />
          </p>
        </label>

        <button
          className="
            mt-3.5 
            bg-blue-500 
            text-white 
            text-[15px] 
            border-none 
            rounded-lg 
            py-2.5 
            font-medium 
            cursor-pointer
          "
        >
          작성/수정완료
        </button>
      </form>
    </Layout>
  );
}

export const Route = createFileRoute("/post")({
  component: Post,
});
