import { createFileRoute } from "@tanstack/react-router";
import Layout from "../component/Layout";
import React from "react";

export default function Post() {
  return (
    <Layout>
      <form
        className="
        max-w-[500px] 
        mx-auto
        flex 
        flex-col 
        gap-3.5
      "
      >
        <div
          className="
        bg-gray-300
        h-[250px]
        w-full
        rounded-[15px]
      "
        />
        <div>
          <h1
            className="
          text-[30px] 
          font-bold 
          mb-2
            "
          >
            제목
          </h1>
          <div
            className="
            flex 
            items-center
            text-[15px] 
           
            font-medium"
          >
            홍길동 | 0000년 00월 00일 |
            <div
              className="
            flex
            gap-[5px]
            ml-[5px]"
            >
              <button
                className="
                bg-[#4B7EFF]
                text-white
                font-bold
                rounded-[5px]
                py-[2px]
                px-[5px]
                "
              >
                #공동구매
              </button>
              <button
                className="
                bg-[#4B7EFF]
                text-white
                font-bold
                rounded-[5px]
                py-[2px]
                px-[5px]
                "
              >
                #공동구매
              </button>
            </div>
          </div>

          <div
            className="
            flex
            items-center
            gap-[10px]"
          >
            <img
              src="/post icons/user.svg"
              alt="login profile"
              className="
            h-[20px]
            w-[20px]
            object-contain
            block
          "
            />
            NN/NN
          </div>
          <div
            className="
            flex
            items-center
            gap-[10px]"
          >
            <img
              src="/post icons/calendar.svg"
              alt="login profile"
              className="
            h-[20px]
            w-[20px]
            object-contain
            block
          "
            />
            0000년 00월 00일 ~ 0000년 00월 00일
          </div>
        </div>
        <div>
          <h2
            className="
          text-[25px] 
          font-semibold
        "
          >
            세부 내용
          </h2>
          <label
            className="
          font-medium 
          text-[15px]
        "
          >
            이것저것
          </label>
        </div>

        <div>
          <h2
            className="
          text-[25px] 
          font-semibold
        "
          >
            참여자
          </h2>
          <div
            className="
        bg-white
        h-[250px]
        w-full
        rounded-[15px]
        flex
        gap-[5px]
      "
          >
            <div
              className="
            bg-[#E5EDFA]
            h-[66px]
            w-[59px]
            rounded-[7.6px]
            flex
            flex-col
            gap-[2px]
            items-center
            justify-center
        "
            >
              <div
                className="
                    bg-white
                    h-[43px]
                    w-[43px]
                    rounded-full

                    "
              />
              <div
                className="
                text-[8px]"
              >
                홍길동
              </div>
            </div>
            <div
              className="
            bg-[#D9D9D9]
            h-[66px]
            w-[59px]
            rounded-[7.6px]
            flex
            flex-col
            gap-[2px]
            items-center
            justify-center
        "
            >
              <div
                className="
                    bg-white
                    h-[43px]
                    w-[43px]
                    rounded-full

                    "
              />
              <div
                className="
                text-[8px]"
              >
                홍길동
              </div>
            </div>
            <div
              className="
            bg-[#D9D9D9]
            h-[66px]
            w-[59px]
            rounded-[7.6px]
            flex
            flex-col
            gap-[2px]
            items-center
            justify-center
        "
            >
              <div
                className="
                    bg-white
                    h-[43px]
                    w-[43px]
                    rounded-full

                    "
              />
              <div
                className="
                text-[8px]"
              >
                홍길동
              </div>
            </div>
            <div
              className="
            bg-[#D9D9D9]
            h-[66px]
            w-[59px]
            rounded-[7.6px]
            flex
            flex-col
            gap-[2px]
            items-center
            justify-center
        "
            >
              <div
                className="
                    bg-white
                    h-[43px]
                    w-[43px]
                    rounded-full

                    "
              />
              <div
                className="
                text-[8px]"
              >
                홍길동
              </div>
            </div>
            <div
              className="
            bg-[#D9D9D9]
            h-[66px]
            w-[59px]
            rounded-[7.6px]
            flex
            flex-col
            gap-[2px]
            items-center
            justify-center
        "
            >
              <div
                className="
                    bg-white
                    h-[43px]
                    w-[43px]
                    rounded-full

                    "
              />
              <div
                className="
                text-[8px]"
              >
                홍길동
              </div>
            </div>
            <div
              className="
            bg-[#D9D9D9]
            h-[66px]
            w-[59px]
            rounded-[7.6px]
            flex
            flex-col
            gap-[2px]
            items-center
            justify-center
        "
            >
              <div
                className="
                    bg-white
                    h-[43px]
                    w-[43px]
                    rounded-full

                    "
              />
              <div
                className="
                text-[8px]"
              >
                홍길동
              </div>
            </div>
            <div
              className="
            bg-[#D9D9D9]
            h-[66px]
            w-[59px]
            rounded-[7.6px]
            flex
            flex-col
            gap-[2px]
            items-center
            justify-center
        "
            >
              <div
                className="
                    bg-white
                    h-[43px]
                    w-[43px]
                    rounded-full

                    "
              />
              <div
                className="
                text-[8px]"
              >
                홍길동
              </div>
            </div>
          </div>
        </div>

        <button
          className="
            mt-3.5 
            bg-blue-500 
            text-white 
            text-[15px] 
            border-none 
            rounded-lg 
            py-2.5 
            font-medium 
            cursor-pointer
          "
        >
          참여하기
        </button>
      </form>
    </Layout>
  );
}

export const Route = createFileRoute("/post")({
  component: Post,
});
