import { createFileRoute } from "@tanstack/react-router";
import Layout from "../component/Layout";
import React from "react";
import api from "../api/api";

export const Route = createFileRoute("/write")({
  component: WriteComponent,
});

function WriteComponent() {
  return (
    <Layout>
      <form
        onSubmit={() => {
          event.preventDefault();
          api();
        }}
        className="
        max-w-[420px] 
        mx-auto 
        mt-10 
        flex 
        flex-col 
        gap-3.5
      "
      >
        <h1
          className="
          text-[26px] 
          font-bold 
          mb-2
        "
        >
          게시글 작성
        </h1>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          제목
          <p>
            <input
              type="text"
              className="
                w-full 
                text-[15px] 
                p-1.5 
                rounded-md 
                border-2 
                border-gray-800 
                mt-1
              "
            />
          </p>
        </label>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          인원
          <p>
            <input
              type="number"
              className="
                w-[70px] 
                text-[15px] 
                p-1.5 
                rounded-md 
                border-2 
                border-gray-800 
                mt-1
              "
            />
          </p>
        </label>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          기간
          <p>
            <input
              type="text"
              className="
                w-[90px] 
                text-[15px] 
                p-1.5 
                rounded-md 
                border-2 
                border-blue-400 
                mt-1
              "
            />
          </p>
        </label>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          내용
          <p>
            <textarea
              rows={6}
              className="
                w-full 
                text-[15px] 
                p-1.5 
                rounded-lg 
                border-2 
                border-gray-800 
                mt-1 
                resize-y
              "
            />
          </p>
        </label>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          이미지 추가
          <p>
            <input
              type="text"
              className="
                w-full 
                text-[15px] 
                p-1.5 
                rounded-md 
                border-2 
                border-gray-800 
                mt-1
              "
            />
          </p>
        </label>
        <label
          className="
          font-medium 
          text-[15px]
        "
        >
          분류 태그
          <p>
            <input
              type="text"
              className="
                w-[100px] 
                text-[15px] 
                p-1.5 
                rounded-md 
                border-2 
                border-blue-400 
                mt-1
              "
            />
          </p>
        </label>
        <button
          type="submit"
          className="
            mt-3.5 
            bg-blue-500 
            text-white 
            text-[15px] 
            border-none 
            rounded-lg 
            py-2.5 
            font-medium 
            cursor-pointer
          "
        >
          작성/수정완료
        </button>
      </form>
    </Layout>
  );
}
