/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WriteImport } from './routes/write'
import { Route as RoommatePostImport } from './routes/roommatePost'
import { Route as PostImport } from './routes/post'
import { Route as MyprofileImport } from './routes/myprofile'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WriteRoute = WriteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRoute,
} as any)

const RoommatePostRoute = RoommatePostImport.update({
  id: '/roommatePost',
  path: '/roommatePost',
  getParentRoute: () => rootRoute,
} as any)

const PostRoute = PostImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRoute,
} as any)

const MyprofileRoute = MyprofileImport.update({
  id: '/myprofile',
  path: '/myprofile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/myprofile': {
      id: '/myprofile'
      path: '/myprofile'
      fullPath: '/myprofile'
      preLoaderRoute: typeof MyprofileImport
      parentRoute: typeof rootRoute
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostImport
      parentRoute: typeof rootRoute
    }
    '/roommatePost': {
      id: '/roommatePost'
      path: '/roommatePost'
      fullPath: '/roommatePost'
      preLoaderRoute: typeof RoommatePostImport
      parentRoute: typeof rootRoute
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/myprofile': typeof MyprofileRoute
  '/post': typeof PostRoute
  '/roommatePost': typeof RoommatePostRoute
  '/write': typeof WriteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/myprofile': typeof MyprofileRoute
  '/post': typeof PostRoute
  '/roommatePost': typeof RoommatePostRoute
  '/write': typeof WriteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/myprofile': typeof MyprofileRoute
  '/post': typeof PostRoute
  '/roommatePost': typeof RoommatePostRoute
  '/write': typeof WriteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/myprofile'
    | '/post'
    | '/roommatePost'
    | '/write'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/myprofile' | '/post' | '/roommatePost' | '/write'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/myprofile'
    | '/post'
    | '/roommatePost'
    | '/write'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyprofileRoute: typeof MyprofileRoute
  PostRoute: typeof PostRoute
  RoommatePostRoute: typeof RoommatePostRoute
  WriteRoute: typeof WriteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyprofileRoute: MyprofileRoute,
  PostRoute: PostRoute,
  RoommatePostRoute: RoommatePostRoute,
  WriteRoute: WriteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/login",
        "/myprofile",
        "/post",
        "/roommatePost",
        "/write"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/login": {
      "filePath": "login.jsx"
    },
    "/myprofile": {
      "filePath": "myprofile.jsx"
    },
    "/post": {
      "filePath": "post.jsx"
    },
    "/roommatePost": {
      "filePath": "roommatePost.jsx"
    },
    "/write": {
      "filePath": "write.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
