/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WriteImport } from './routes/write'
import { Route as MyProfileImport } from './routes/myProfile'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WriteRoute = WriteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRoute,
} as any)

const MyProfileRoute = MyProfileImport.update({
  id: '/myProfile',
  path: '/myProfile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/myProfile': {
      id: '/myProfile'
      path: '/myProfile'
      fullPath: '/myProfile'
      preLoaderRoute: typeof MyProfileImport
      parentRoute: typeof rootRoute
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/myProfile': typeof MyProfileRoute
  '/write': typeof WriteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/myProfile': typeof MyProfileRoute
  '/write': typeof WriteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/myProfile': typeof MyProfileRoute
  '/write': typeof WriteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/myProfile' | '/write'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/myProfile' | '/write'
  id: '__root__' | '/' | '/login' | '/myProfile' | '/write'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyProfileRoute: typeof MyProfileRoute
  WriteRoute: typeof WriteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyProfileRoute: MyProfileRoute,
  WriteRoute: WriteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/login",
        "/myProfile",
        "/write"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/login": {
      "filePath": "login.jsx"
    },
    "/myProfile": {
      "filePath": "myProfile.jsx"
    },
    "/write": {
      "filePath": "write.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
